name: stepbit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  dio: ^5.1.2
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  flutter_animate: ^4.1.1+1
  animated_digit: ^3.2.1
  activity_ring: ^0.3.0
  dio_cache_interceptor: ^3.4.2
  google_maps_flutter: ^2.3.0
  uuid: ^3.0.7
  geolocator: ^9.0.2
  map_launcher: ^2.5.0+1
  geocoding: ^2.1.0
  floor: ^1.4.2
  sqflite: ^2.2.8+4
  provider: ^6.0.5
  flutter_expandable_fab: ^1.8.1
  qr_flutter: ^4.1.0
  easy_settings: ^1.0.0
  property_change_notifier: ^0.3.0
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
